"""empty message

Revision ID: a1373dceb99d
Revises: 35023c77ce54
Create Date: 2024-01-16 19:10:51.142549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1373dceb99d'
down_revision = '35023c77ce54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('european_option_portfolio', sa.JSON(), nullable=True))
        batch_op.drop_column('portfolio_value')
        batch_op.drop_column('portfolio_stocks')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('portfolio_stocks', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('portfolio_value', sa.FLOAT(), nullable=True))
        batch_op.drop_column('european_option_portfolio')

    # ### end Alembic commands ###
