"""empty message

Revision ID: d2e80518db9c
Revises: a1373dceb99d
Create Date: 2024-01-16 22:24:39.397640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2e80518db9c'
down_revision = 'a1373dceb99d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('american_option_portfolio', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('american_option_portfolio')

    # ### end Alembic commands ###
